application: rasmuserik
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /wn/LICENSE_FOR_DATABASE
  static_files: LICENSE_FOR_DATABASE
  upload: LICENSE_FOR_DATABASE
  mime_type: text/plain
- url: /wn/json
  script: jsondump.py
- url: /wn/upload
  script: upload.py
- url: /wn/thesaurus
  script: thesaurus.py
- url: /wn
  script: thesaurus.py
- url: /
  script: index.py
