application: rasmuserik
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

skip_files: 
- ^jquery-mobile
- ^database.*
handlers:
- url: /
  script: index.py
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /wn/static
  static_dir: static
- url: /wn/LICENSE_FOR_DATABASE
  static_files: LICENSE_FOR_DATABASE
  upload: LICENSE_FOR_DATABASE
  mime_type: text/plain
- url: /wn/thesaurus
  script: thesaurus.py
